
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"

/* event handler declarations */
void view1_button1_onpressed(uib_view1_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_view1_create(Evas_Object* parent, void* create_callback_param) {
	elm_win_indicator_mode_set(get_window(parent), ELM_WIN_INDICATOR_SHOW);
	uib_view1_view_context* vc = calloc(1, sizeof(uib_view1_view_context));
	vc->parent = parent;
	vc->view_name = "view1";
	if (!vc->box1) {
		vc->box1= elm_box_add(parent);
		vc->root_container = vc->box1;	}
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	uib_views_get_instance()->set_targeted_view(vc->view_name);

	//bind event handler
	evas_object_smart_callback_add(vc->button1, "pressed", (Evas_Smart_Cb)view1_button1_onpressed, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);

	return (uib_view_context*)vc;
}
void uib_view1_config_HD_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_view1_view_context* vc = (uib_view1_view_context*)uib_app_manager->find_view_context("view1");
	if(vc->box1) {
		elm_box_homogeneous_set(vc->box1, EINA_FALSE);
		elm_box_horizontal_set(vc->box1, EINA_FALSE);
		elm_box_padding_set(vc->box1,0,0);
		evas_object_size_hint_align_set(vc->box1, 0.5, 0.5);
		evas_object_size_hint_weight_set(vc->box1, 1.0, 1.0);
		if (!vc->button1) {
			vc->button1 = elm_button_add(vc->box1);
		}
		if (vc->button1) {
			evas_object_size_hint_align_set(vc->button1, 0.5, 0.5);			evas_object_size_hint_weight_set(vc->button1, .0, .0);			elm_object_text_set(vc->button1,_UIB_LOCALE("Tap"));
			elm_object_style_set(vc->button1,"circle");
			evas_object_show(vc->button1);
		}
		if (!vc->label1) {
			vc->label1 = elm_label_add(vc->box1);
		}
		if(vc->label1) {
			evas_object_size_hint_align_set(vc->label1, 0.5, 0.5);			evas_object_size_hint_weight_set(vc->label1, .0, .0);			elm_object_text_set(vc->label1,_UIB_LOCALE("Latitude Initial: N/A"));
			elm_label_ellipsis_set(vc->label1, EINA_FALSE);
			evas_object_show(vc->label1);
		}
		if (!vc->label2) {
			vc->label2 = elm_label_add(vc->box1);
		}
		if(vc->label2) {
			evas_object_size_hint_align_set(vc->label2, 0.5, 0.5);			evas_object_size_hint_weight_set(vc->label2, .0, .0);			elm_object_text_set(vc->label2,_UIB_LOCALE("Longitude Initial: N/A"));
			elm_label_line_wrap_set(vc->label2, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label2,0);
			elm_label_ellipsis_set(vc->label2, EINA_FALSE);
			evas_object_show(vc->label2);
		}
		if (!vc->label3) {
			vc->label3 = elm_label_add(vc->box1);
		}
		if(vc->label3) {
			evas_object_size_hint_align_set(vc->label3, 0.5, 0.5);			evas_object_size_hint_weight_set(vc->label3, .0, .0);			elm_object_text_set(vc->label3,_UIB_LOCALE("Latitude Final: N/A"));
			elm_label_line_wrap_set(vc->label3, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label3,0);
			elm_label_ellipsis_set(vc->label3, EINA_FALSE);
			evas_object_show(vc->label3);
		}
		if (!vc->label4) {
			vc->label4 = elm_label_add(vc->box1);
		}
		if(vc->label4) {
			evas_object_size_hint_align_set(vc->label4, 0.5, -1.0);			evas_object_size_hint_weight_set(vc->label4, .0, .0);			elm_object_text_set(vc->label4,_UIB_LOCALE("Longitude Final: N/A"));
			elm_label_line_wrap_set(vc->label4, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label4,0);
			elm_label_ellipsis_set(vc->label4, EINA_FALSE);
			evas_object_show(vc->label4);
		}
		if (!vc->labelDistance) {
			vc->labelDistance = elm_label_add(vc->box1);
		}
		if(vc->labelDistance) {
			evas_object_size_hint_align_set(vc->labelDistance, 0.5, -1.0);			evas_object_size_hint_weight_set(vc->labelDistance, .0, .0);			elm_object_text_set(vc->labelDistance,_UIB_LOCALE("Distance: N/A"));
			elm_label_line_wrap_set(vc->labelDistance, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->labelDistance,0);
			elm_label_ellipsis_set(vc->labelDistance, EINA_FALSE);
			evas_object_show(vc->labelDistance);
		}
		elm_box_pack_end(vc->box1, vc->button1);
		elm_box_pack_end(vc->box1, vc->label1);
		elm_box_pack_end(vc->box1, vc->label2);
		elm_box_pack_end(vc->box1, vc->label3);
		elm_box_pack_end(vc->box1, vc->label4);
		elm_box_pack_end(vc->box1, vc->labelDistance);
		evas_object_show(vc->box1);
	}
}

