/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include <dlog.h>
#include <locations.h>


double distance;
double altitude;
double latitude;
double longitude;
double climb;
double direction;
double speed;
double horizontal;
double vertical;
location_accuracy_level_e level;
time_t timestamp;

double fdistance;
double faltitude;
double flatitude;
double flongitude;
double fclimb;
double fdirection;
double fspeed;
double fhorizontal;
double fvertical;
location_accuracy_level_e flevel;
time_t ftimestamp;

char Log_Tag[15] = "AvoidRickshaw\0";

location_manager_h manager;

typedef struct _uib_view1_control_context
{
	/* add your variables here */

} uib_view1_control_context;

uib_view1_view_context *view;

/**
 * @brief button was pressed.
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
location_service_state_e service_state = LOCATIONS_SERVICE_ENABLED;

static void state_changed_cb(location_service_state_e state, void *user_data)  //Update GPS Data
{
    service_state = state;
}

static void position_updated_cb(double flatitude, double flongitude, double faltitude, time_t ftimestamp, void *user_data)                                    //Update position after 2 second interval
{

    char latitude_string[100];
    char longitude_string[100];
    char distance_string[100];


    location_manager_get_last_location(manager, &faltitude, &flatitude, &flongitude,
        		                                        &fclimb, &fdirection, &fspeed, &flevel, &fhorizontal,
        		                                         &fvertical, &ftimestamp); //Return current location in real time

    snprintf(latitude_string, 100, "Latitude Final: %lf", flatitude);              //Double to String conversion
    snprintf(longitude_string, 100, "Longitude Final: %lf", flongitude);

    elm_object_text_set(view->label3,latitude_string);						//Changing label
    elm_object_text_set(view->label4,longitude_string);

    location_manager_get_distance(latitude, longitude, flatitude, flongitude, &distance);

    dlog_print(DLOG_DEBUG, Log_Tag,"Longitude: %lf, Latitude: %lf, Distance : %lf",
    													flongitude, flatitude, distance);

    snprintf(distance_string, 100, "Distance: %lf", distance);

    elm_object_text_set(view->labelDistance, distance_string);
}

void view1_button1_onpressed(uib_view1_view_context *viewContext, Evas_Object *obj, void *event_info)
{

		view = viewContext;

		location_manager_h manager;
		location_manager_create(LOCATIONS_METHOD_HYBRID, &manager);

		int status = location_manager_set_service_state_changed_cb(manager, state_changed_cb, NULL);

		dlog_print(DLOG_DEBUG,Log_Tag,"Status: %d", status);

		location_manager_set_position_updated_cb(manager, position_updated_cb, 3, NULL);

		location_manager_start(manager);

		dlog_print(DLOG_DEBUG, Log_Tag, "Calling location method...");

		location_manager_get_last_location(manager, &altitude, &latitude, &longitude,
											   &climb, &direction, &speed, &level, &horizontal,
											   &vertical, &timestamp);

		 if (service_state == LOCATIONS_SERVICE_ENABLED) {
			 dlog_print(DLOG_DEBUG, Log_Tag,"LOCATIONS_SERVICE_ENABLED");
			 dlog_print(DLOG_DEBUG, Log_Tag,"Latitude: %lf, Long: %lf", latitude, longitude);
		 }

		 char latitude_string[100];
		 char longitude_string[100];

		 snprintf(latitude_string, 100, "Latitude Initial: %lf", latitude);
		 snprintf(longitude_string, 100, "Longitude Initial: %lf", longitude);

		 elm_object_text_set(viewContext->label1, latitude_string);
		 elm_object_text_set(viewContext->label2, longitude_string);

}

